/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./a_dm_in/**/*.{html,js}",
    "./public/**/*.{html,js}"
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "tertiary-container": "#ad6033",
              "primary-fixed-dim": "#6ad7d7",
              "error": "#ba1a1a",
              "surface-container-high": "#e4e9e8",
              "background": "#f6faf9",
              "primary-container": "#008282",
              "on-primary": "#ffffff",
              "surface-tint": "#006a6a",
              "surface-container-low": "#f0f5f4",
              "on-error": "#ffffff",
              "on-tertiary": "#ffffff",
              "on-surface-variant": "#3d4949",
              "on-secondary": "#ffffff",
              "tertiary-fixed": "#ffdbca",
              "surface-container-lowest": "#ffffff",
              "inverse-on-surface": "#edf2f1",
              "error-container": "#ffdad6",
              "on-tertiary-fixed-variant": "#743408",
              "inverse-surface": "#2c3131",
              "surface-container-highest": "#dfe3e3",
              "primary-fixed": "#88f4f3",
              "surface-container": "#eaefee",
              "secondary-fixed-dim": "#b7c8e1",
              "on-primary-container": "#f3fffe",
              "on-primary-fixed": "#002020",
              "secondary-fixed": "#d3e4fe",
              "on-surface": "#171d1c",
              "surface-bright": "#f6faf9",
              "on-error-container": "#93000a",
              "inverse-primary": "#6ad7d7",
              "tertiary-fixed-dim": "#ffb68f",
              "surface-dim": "#d6dbda",
              "on-primary-fixed-variant": "#004f4f",
              "tertiary": "#8f491d",
              "surface-variant": "#dfe3e3",
              "on-secondary-container": "#54647a",
              "primary": "#006767",
              "on-secondary-fixed": "#0b1c30",
              "outline": "#6d7979",
              "on-tertiary-fixed": "#331100",
              "on-tertiary-container": "#fffbff",
              "on-secondary-fixed-variant": "#38485d",
              "on-background": "#171d1c",
              "secondary": "#505f76",
              "outline-variant": "#bcc9c8",
              "surface": "#f6faf9",
              "secondary-container": "#d0e1fb"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "sm": "8px",
              "margin-mobile": "16px",
              "base": "8px",
              "3xl": "64px",
              "margin-desktop": "32px",
              "container-max": "1440px",
              "xl": "32px",
              "gutter": "24px",
              "md": "16px",
              "lg": "24px",
              "xs": "4px",
              "2xl": "48px"
      },
      "fontFamily": {
              "body-lg": ["Inter"],
              "title-md": ["Inter"],
              "headline-lg": ["Inter"],
              "label-sm": ["Inter"],
              "label-md": ["Inter"],
              "body-sm": ["Inter"],
              "headline-lg-mobile": ["Inter"],
              "title-lg": ["Inter"],
              "display-lg": ["Inter"],
              "headline-md": ["Inter"],
              "body-md": ["Inter"]
      },
      "fontSize": {
              "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
              "title-md": ["16px", {"lineHeight": "24px", "fontWeight": "600"}],
              "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
              "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
              "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500"}],
              "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
              "headline-lg-mobile": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "title-lg": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
              "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
