tailwind.config = {
        darkMode: "class",
        theme: {
          extend: {
            "colors": {
                    "surface": "#f6faf9",
                    "surface-container-lowest": "#ffffff",
                    "primary": "#006767",
                    "tertiary": "#8f491d",
                    "on-tertiary": "#ffffff",
                    "on-background": "#171d1c",
                    "on-tertiary-fixed": "#331100",
                    "primary-fixed": "#88f4f3",
                    "surface-container-low": "#f0f5f4",
                    "on-primary": "#ffffff",
                    "error": "#ba1a1a",
                    "inverse-surface": "#2c3131",
                    "on-secondary-fixed-variant": "#38485d",
                    "surface-bright": "#f6faf9",
                    "primary-container": "#008282",
                    "background": "#f6faf9",
                    "inverse-on-surface": "#edf2f1",
                    "on-secondary-fixed": "#0b1c30",
                    "primary-fixed-dim": "#6ad7d7",
                    "on-secondary-container": "#54647a",
                    "on-secondary": "#ffffff",
                    "on-error-container": "#93000a",
                    "inverse-primary": "#6ad7d7",
                    "secondary": "#505f76",
                    "tertiary-fixed": "#ffdbca",
                    "on-tertiary-container": "#fffbff",
                    "surface-container-highest": "#dfe3e3",
                    "on-primary-fixed-variant": "#004f4f",
                    "surface-container": "#eaefee",
                    "on-primary-container": "#f3fffe",
                    "tertiary-fixed-dim": "#ffb68f",
                    "on-error": "#ffffff",
                    "outline": "#6d7979",
                    "on-tertiary-fixed-variant": "#743408",
                    "surface-dim": "#d6dbda",
                    "surface-container-high": "#e4e9e8",
                    "on-surface-variant": "#3d4949",
                    "tertiary-container": "#ad6033",
                    "secondary-fixed-dim": "#b7c8e1",
                    "surface-tint": "#006a6a",
                    "secondary-container": "#d0e1fb",
                    "on-primary-fixed": "#002020",
                    "outline-variant": "#bcc9c8",
                    "on-surface": "#171d1c",
                    "error-container": "#ffdad6",
                    "surface-variant": "#dfe3e3",
                    "secondary-fixed": "#d3e4fe"
            },
            "borderRadius": {
                    "DEFAULT": "0.25rem",
                    "lg": "0.5rem",
                    "xl": "0.75rem",
                    "full": "9999px"
            },
            "spacing": {
                    "md": "16px",
                    "container-max": "1440px",
                    "margin-mobile": "16px",
                    "gutter": "24px",
                    "2xl": "48px",
                    "xl": "32px",
                    "sm": "8px",
                    "margin-desktop": "32px",
                    "lg": "24px",
                    "base": "8px",
                    "3xl": "64px",
                    "xs": "4px"
            },
            "fontFamily": {
                    "headline-lg": ["Inter"],
                    "headline-md": ["Inter"],
                    "body-md": ["Inter"],
                    "body-sm": ["Inter"],
                    "title-lg": ["Inter"],
                    "display-lg": ["Inter"],
                    "headline-lg-mobile": ["Inter"],
                    "title-md": ["Inter"],
                    "label-sm": ["Inter"],
                    "body-lg": ["Inter"],
                    "label-md": ["Inter"]
            },
            "fontSize": {
                    "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
                    "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
                    "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                    "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
                    "title-lg": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
                    "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                    "headline-lg-mobile": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
                    "title-md": ["16px", {"lineHeight": "24px", "fontWeight": "600"}],
                    "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
                    "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                    "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500"}]
            }
          },
        },
      }